* Clojure Overstapservice
** 0.125 MvA: Inleiding
*** Aanleiding
Praatje Rich Hickey op Java One 2 juni 2015
*** Doel van artikel
Update van Clojure ecosysteem. Toevoegingen. Ontwikkelingen. Aanreiken
van middelen om te switchen van Java -> Clojure, teneinde te
profiteren van de voordelen. Je zou het kunnen beschouwen als een overstapservice.

*** Wat is Clojure
**** Kern = immutability, persistent data structures
**** Omarmen van hosting platform
**** (Composable) libraries ipv frameworks
**** MvA: Van Rich Hickey naar Cognitect
Geestelijk vader Rich Hickey
Rich heeft een jaar besteed om de taal te ontwikkelen
Voorbeeld van Hammock Driven Development
Het denkwerk werd aanvankelijk opgepakt in kleine kring
Van kleinschalige community naar 'big business' o.l.v. Cognitect
Rentmeesterschap van Relevance van Clojure.
Cognitect.
Support.

**** Clojure is voor sommige bedrijven een strategische keuze geworden
***** Puppet Labs
http://blog.cognitect.com/blog/2015/7/28/a-puppet-labs-revolution-powered-by-clojure
***** Otto.de
http://dev.otto.de/2015/06/23/a-tale-of-two-lambdas-2/
***** Wall Mart
http://blog.cognitect.com/blog/2015/6/30/walmart-runs-clojure-at-scale
**** Eigenzinnig/anders
Alternatief voor Java
** 0.25 MB: Voordelen van overstappen
*** Een taal beheersen voor server en client
*** Herbruikbaarheid van code/data op server en client
*** geen callback hell op client
*** Minder complexiteit (uit zich in minder regels code)
*** Ontwikkelen met directe feedback
***** REPL
***** figwheel
                                   
** 0.25 MB: Full stack web development
*** Nieuwe toevoegingen, naar een Clojure ecosysteem
**** ClojureScript
***** React -> Reagent / Om etc.
**** core.async
***** http-cljs
**** reader conditionals (.cljc)
**** Datomic
**** Schema
** 0.25 MvA: Het is makkelijk om over te stappen
*** Wervende tekst, parodie op commercials
"Met Clojure kun je tot wel 10K regels code per jaar besparen"
*** Weliswaar geen certificeringspad, maar goede introducties zijn er wel (zie kader)
*** Gedeeltelijk 'vervangen', hetzij van front-end, hetzij van back-end
**** Microservices
*** Blijft JVM
**** Clojure is eigenlijk een Java library
*** Acties om over te stappen
In kader plaatsen:
**** MOOC
***** Functional Programming with Clojure
http://mooc.fi/courses/2014/clojure/
**** Boeken
***** O'Reilly
Vroeger hoefde je niet te proberen om een voorstel in te dienen voor een boek over Lisp.
Nu zijn voert de uitgever meerdere Clojure titels:
http://search.oreilly.com/?q=clojure&x=0&y=0
****** Living Clojure
Andere uitgevers:
http://www.amazon.com/Living-Clojure-Carin-Meier/dp/1491909048
****** Clojure for the Brave and True
http://www.amazon.com/Clojure-Brave-True-Ultimate-Programmer/dp/1593275919

**** Clojure Cursus
***** Clojure for the Brave and True
http://www.braveclojure.com
***** Immutable Webapp repo
***** O'Reilly
Clojure Inside Out
http://shop.oreilly.com/product/0636920030409.do
**** Talks
***** Rich Hickey et al
**** Transitioning
***** Clojure Landscape from Java
https://github.com/pjagielski/clojure-landscape-from-java

** 0.125 Samen: Conclusie
*** Goed idee om over te stappen
**** Voordelen
**** Makkelijk om over te stappen
